wandb_version: 1

colsample_bylevel:
  value: 1
depth:
  value: 15
iterations:
  value: 5000
learning_rate:
  value: 0.0347420782431242
min_data_in_leaf:
  value: 1
subsample:
  value: 0.9314934016164774
