wandb_version: 1

colsample_bylevel:
  value: 1
depth:
  value: 6
iterations:
  value: 2000
learning_rate:
  value: 0.05872681962336131
min_data_in_leaf:
  value: 20
subsample:
  value: 0.9298209493231488
