wandb_version: 1

colsample_bylevel:
  value: 1
depth:
  value: 10
iterations:
  value: 2000
learning_rate:
  value: 0.005700017655707702
min_data_in_leaf:
  value: 20
subsample:
  value: 0.8205691328875538
