wandb_version: 1

colsample_bylevel:
  value: 0.5
depth:
  value: 10
iterations:
  value: 2000
learning_rate:
  value: 0.0982227833265532
min_data_in_leaf:
  value: 1
subsample:
  value: 0.9486348900020998
