wandb_version: 1

colsample_bylevel:
  value: 1
depth:
  value: 10
iterations:
  value: 2000
learning_rate:
  value: 0.07500186683843636
min_data_in_leaf:
  value: 20
subsample:
  value: 0.8977894034291081
