wandb_version: 1

colsample_bylevel:
  value: 0.5
depth:
  value: 6
iterations:
  value: 1000
learning_rate:
  value: 0.0076132514313715614
min_data_in_leaf:
  value: 20
subsample:
  value: 0.8307096019770898
