wandb_version: 1

colsample_bylevel:
  value: 1
depth:
  value: 6
iterations:
  value: 1000
learning_rate:
  value: 0.01634779896952864
min_data_in_leaf:
  value: 1
subsample:
  value: 0.9012140942790828
