wandb_version: 1

colsample_bylevel:
  value: 0.5
depth:
  value: 10
iterations:
  value: 2000
learning_rate:
  value: 0.07794058540578239
min_data_in_leaf:
  value: 20
subsample:
  value: 0.979559057003342
