wandb_version: 1

colsample_bylevel:
  value: 1
depth:
  value: 10
iterations:
  value: 2000
learning_rate:
  value: 0.08697118415790321
min_data_in_leaf:
  value: 1
subsample:
  value: 0.9075508343200692
