wandb_version: 1

colsample_bylevel:
  value: 0.5
depth:
  value: 2
iterations:
  value: 1000
learning_rate:
  value: 0.015453014891405522
min_data_in_leaf:
  value: 20
subsample:
  value: 0.9567991427013448
