wandb_version: 1

colsample_bylevel:
  value: 0.5
depth:
  value: 2
iterations:
  value: 1000
learning_rate:
  value: 0.006353472379822815
min_data_in_leaf:
  value: 20
subsample:
  value: 0.8760418601093677
