wandb_version: 1

colsample_bylevel:
  value: 0.5
depth:
  value: 10
iterations:
  value: 1000
learning_rate:
  value: 0.04624529381275665
min_data_in_leaf:
  value: 1
subsample:
  value: 0.863300206343103
