wandb_version: 1

colsample_bylevel:
  value: 0.5
depth:
  value: 6
iterations:
  value: 1000
learning_rate:
  value: 0.013427695758938755
min_data_in_leaf:
  value: 1
subsample:
  value: 0.9593749164320252
