wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.12.4
    cli_version: 0.17.5
    framework: catboost
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1722558808
    t:
      1:
      - 5
      - 7
      - 53
      - 55
      2:
      - 5
      - 7
      - 53
      - 55
      3:
      - 2
      - 23
      - 37
      4: 3.12.4
      5: 0.17.5
      8:
      - 1
      - 3
      - 5
      13: windows-amd64
colsample_bylevel:
  desc: null
  value: 1
depth:
  desc: null
  value: 10
iterations:
  desc: null
  value: 2000
learning_rate:
  desc: null
  value: 0.012184047003739151
min_data_in_leaf:
  desc: null
  value: 20
subsample:
  desc: null
  value: 0.8713085369702779
