wandb_version: 1

colsample_bylevel:
  value: 0.5
depth:
  value: 2
iterations:
  value: 1000
learning_rate:
  value: 0.08270812901812892
min_data_in_leaf:
  value: 1
subsample:
  value: 0.9803219298593951
